language: ruby

rvm:
  - 2.2.2

script:
  - bundle exec rake db:test:prepare
  - bundle exec rake spec
  - bundle exec rake cucumber:all

branches:
  only:
    - master
    - dev

notifications:
  email:
    on_success: change
    on_failure: always