language: ruby

rvm:
  - 2.2.2

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3

bundler_args:
  - --without production

script:
  - bundle exec rake db:test:prepare
  - bundle exec rake spec
  - bundle exec rake cucumber:all

branches:
  only:
    - master
    - dev

notifications:
  email:
    on_success: change
    on_failure: always
